[[module.imports]]
  path = "github.com/biati-digital/glightbox"

  [[module.imports.mounts]]
    source = "dist/css/glightbox.min.css"
    target = "static/css/glightbox.min.css"
  [[module.imports.mounts]]
    source = "dist/js/glightbox.min.js"
    target = "static/js/glightbox.min.js"